on:
  push:
    branches-ignore:
      - main
name: CI
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: blang/latex:ubuntu
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Build poster
        run: pdflatex -shell-escape main.tex
      - name: Check pdf files
        run: file main.pdf | grep -q ' PDF '
